.TH Feng 1 "May 15, 2008" "Feng Streaming Server" "LScube Project"
.SH NAME
\fBFeng\fP \- multimedia streaming server
.SH SYNOPSIS
.B feng
.RI -f " config"
.RI -q
.RI -s
.RI -v
.RI -h
.SH DESCRIPTION
This manual page documents briefly the \fBFeng\fP streaming server.
.PP
\fBFeng\fP is a multimedia streaming server compliant with the IETF's
standards for real\-time streaming of multimedia contents over Internet.
\fBFeng\fP implements RTSP \- Real\-Time Streaming Protocol (RFC2326) and
RTP/RTCP \- Real\-Time Transport Protocol/RTP Control Protocol (RFC3550)
supporting the RTP Profile for Audio and Video Conferences with Minimal Control
(RFC3551).
.br
.sp 1
\fBFeng\fP is capable of live streaming using external real\-time audio/video
encoders such as lame, ffmpeg or vlc, even capturing audio and video
streams from live-recording remote hosts using
.BR felix (1).
.PP
.SH OPTIONS
This program follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.BI "\-f, \-\-config " config
Uses the directives in the file \fIconfig\fP
on startup. See CONFIGURATION for details.
.TP
.BI "\-s, \-\-syslog "
Uses the standard system logger facility instead of writing a logfile.
.TP
.BI "\-q, \-\-quiet "
Suppresses the standard output completely.
.TP
.BI "\-v, \-\-verbose "
Outputs messages to standard error, useful for debug purposes.

.SH CONFIGURATION
The configuration file use the same syntax used by
.BR lighttpd (1)
.SH SEE ALSO
\fIOn-line Documentation\fP:
.UH
http://lscube.org/feng
.SH AUTHORS
\fBFeng\fP was written by \fBLScube Team\fP.
.PP
This manual page was written by \fBLScube Team\fP <team@lscube.org>.
.PP
Please check
.UH
http://lscube.org/
for further details.

